#!/bin/bash
mkdir -p $5/{log,shared,res}
donar \
  -a dup2 \
  -c \
  -o $5/shared/onion_services.pub \
  -l $4 \
  -b \
  -r 9000 \
> $5/log/client-donar-stdout.log 2> $5/log/client-donar-stderr.log &
sleep 2

measlat -h 127.13.3.7 -p 9000 > /dev/null 2>&1 # Used to wait for connections
measlat -h 127.13.3.7 -p 9000 -c $1 -i $2 -s $3 > $5/res/dup2.csv 2> $5/log/client-measlat-stderr.log
