#!/bin/bash
mkdir -p $3/{log,shared,res}

donar \
  -a naive \
  -c \
  -o $3/shared/onion_services.pub \
  -l $1 \
  -b \
  -e 5001 \
  -r 5000 \
> $3/log/client-donar-stdout.log 2> $3/log/client-donar-stderr.log &

sleep 1
tail -f $3/log/server-donar-stdout.log | grep -q "=== Our 1 requested circuits are now up ===" \
> $3/log/client-measboot-stdout.log 2> $3/log/client-measboot-stderr.log 

dcall \
  -t filesrc \
  -a file:///assets/i_have_a_dream.mp3 \
  -s fakesink \
  -b 127.0.0.1 \
  -c 5001 \
  -l $2 \
  -d $3/log/client-dcall-gstreamer.log \
> $3/log/client-dcall-stdout.log 2> $3/log/client-dcall-stderr.log
