#!/bin/bash
mkdir -p $5/{log,shared}
cd $5/shared

#echo -e 'authenticate ""\nsetevents extended circ circ_minor stream orconn addrmap status_general status_client guard info notice warn err newdesc descchanged ns status_server stream_bw clients_seen hs_desc network_liveness' | \
#  nc --no-shutdown 127.0.0.1 9051 | \
#  ts \
#> ../log/server-tor-events-stdout.log 2> ../log/server-tor-events-stderr.log &

donar \
  -a dup2 \
  -s \
  -l $4 \
  -e 9000 \
> ../log/server-donar-stdout.log 2> ../log/server-donar-stderr.log &

measlat -h 127.0.0.1 -p 9000 -l -c $1 -i $2 -s $3 > ../log/server-measlat-stdout.log 2> ../log/server-measlat-stderr.log
