#!/bin/bash
mkdir -p $4/{log,shared,res}
donar -a naive -c -o ./shared/onion_services.pub -v -r 9000 > ./log/client-donar-stdout.log 2> ./log/client-donar-stderr.log &
sleep 2

measlat -h 127.13.3.7 -p 9000 > /dev/null 2>&1 # Used to wait for connections
measlat -h 127.13.3.7 -p 9000 -c $1 -i $2 -s $3 > ./res/naive.csv 2> ./log/client-measlat-stderr.log
